// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AkcijeSkoleWebApi.Data.DbModels
{
    public partial class CvrstiObjektiZaObitavanje
    {
        [Key]
        public int IdObjektaZaObitavanje { get; set; }
        public int BrojPredvidenihSpavacihMjesta { get; set; }

        [ForeignKey("IdObjektaZaObitavanje")]
        [InverseProperty("CvrstiObjektiZaObitavanje")]
        public virtual TerenskeLokacije IdObjektaZaObitavanjeNavigation { get; set; }
    }
}