// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AkcijeSkoleWebApi.Models
{
    public partial class CvrstiObjektiZaObitavanje
    {
        public int IdObjektaZaObitavanje { get; set; }
        public int BrojPredvidenihSpavacihMjesta { get; set; }

        public virtual TerenskeLokacije IdObjektaZaObitavanjeNavigation { get; set; }
    }
}