// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AkcijeSkoleWebApi.Models
{
    public partial class MaterijalnePotrebe
    {
        public MaterijalnePotrebe()
        {
            Zahtjevi = new HashSet<Zahtjevi>();
            Akcije = new HashSet<Akcije>();
            Skole = new HashSet<Skole>();
            TerenskeLokacije = new HashSet<TerenskeLokacije>();
        }

        public int IdMaterijalnePotrebe { get; set; }
        public string Naziv { get; set; }
        public int Organizator { get; set; }
        public int Davatelj { get; set; }
        public bool Zadovoljeno { get; set; }
        public double? Kolicina { get; set; }
        public string MjernaJedinica { get; set; }

        public virtual ICollection<Zahtjevi> Zahtjevi { get; set; }

        public virtual ICollection<Akcije> Akcije { get; set; }
        public virtual ICollection<Skole> Skole { get; set; }
        public virtual ICollection<TerenskeLokacije> TerenskeLokacije { get; set; }
    }
}