// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AkcijeSkoleWebApi.Models
{
    public partial class PolazniciAkcije
    {
        public int Polaznik { get; set; }
        public int AkcijaId { get; set; }
        public int AktivnostId { get; set; }

        public virtual Akcije Akcija { get; set; }
        public virtual Aktivnosti Aktivnost { get; set; }
    }
}