// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AkcijeSkoleWebApi.Models
{
    public partial class Skole
    {
        public Skole()
        {
            Edukacije = new HashSet<Edukacije>();
            PolazniciSkole = new HashSet<PolazniciSkole>();
            PrijavljeniPolazniciSkole = new HashSet<PrijavljeniPolazniciSkole>();
            MaterijalnePotreb = new HashSet<MaterijalnePotrebe>();
            TerenskaLokacija = new HashSet<TerenskeLokacije>();
        }

        public int IdSkole { get; set; }
        public string NazivSkole { get; set; }
        public int MjestoPbr { get; set; }
        public int Organizator { get; set; }
        public int KontaktOsoba { get; set; }

        public virtual Mjesta MjestoPbrNavigation { get; set; }
        public virtual ICollection<Edukacije> Edukacije { get; set; }
        public virtual ICollection<PolazniciSkole> PolazniciSkole { get; set; }
        public virtual ICollection<PrijavljeniPolazniciSkole> PrijavljeniPolazniciSkole { get; set; }

        public virtual ICollection<MaterijalnePotrebe> MaterijalnePotreb { get; set; }
        public virtual ICollection<TerenskeLokacije> TerenskaLokacija { get; set; }
    }
}