// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AkcijeSkoleWebApi.Models
{
    public partial class TerenskeLokacije
    {
        public TerenskeLokacije()
        {
            Akcije = new HashSet<Akcije>();
            MaterijalnePotrebe = new HashSet<MaterijalnePotrebe>();
            Skola = new HashSet<Skole>();
        }

        public int IdTerenskeLokacije { get; set; }
        public string NazivTerenskeLokacije { get; set; }
        public byte[] Slika { get; set; }
        public bool ImaSanitarniCvor { get; set; }
        public int MjestoPbr { get; set; }
        public string Opis { get; set; }

        public virtual Mjesta MjestoPbrNavigation { get; set; }
        public virtual CvrstiNamjenskiObjekti CvrstiNamjenskiObjekti { get; set; }
        public virtual CvrstiObjektiZaObitavanje CvrstiObjektiZaObitavanje { get; set; }
        public virtual Logorista Logorista { get; set; }
        public virtual PrivremeniObjekti PrivremeniObjekti { get; set; }

        public virtual ICollection<Akcije> Akcije { get; set; }
        public virtual ICollection<MaterijalnePotrebe> MaterijalnePotrebe { get; set; }
        public virtual ICollection<Skole> Skola { get; set; }
    }
}