// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IzvidaciAkcijeSkoleWebApi.Data.Models
{
    public partial class PolazniciSkole
    {
        [Key]
        public int Polaznik { get; set; }
        [Key]
        public int SkolaId { get; set; }
        [Key]
        public int EdukacijaId { get; set; }

        [ForeignKey("EdukacijaId")]
        [InverseProperty("PolazniciSkole")]
        public virtual Edukacije Edukacija { get; set; }
        [ForeignKey("SkolaId")]
        [InverseProperty("PolazniciSkole")]
        public virtual Skole Skola { get; set; }
    }
}