// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IzvidaciAkcijeSkoleWebApi.Data.Models
{
    public partial class PrivremeniObjekti
    {
        [Key]
        public int IdPrivremeniObjekt { get; set; }
        [Required]
        [Unicode(false)]
        public string Opis { get; set; }

        [ForeignKey("IdPrivremeniObjekt")]
        [InverseProperty("PrivremeniObjekti")]
        public virtual TerenskeLokacije IdPrivremeniObjektNavigation { get; set; }
    }
}