// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IzvidaciAkcijeSkoleWebApi.Data.Models
{
    public partial class Skole
    {
        public Skole()
        {
            Edukacije = new HashSet<Edukacije>();
            PolazniciSkole = new HashSet<PolazniciSkole>();
            PrijavljeniPolazniciSkole = new HashSet<PrijavljeniPolazniciSkole>();
            MaterijalnePotreb = new HashSet<MaterijalnePotrebe>();
            TerenskaLokacija = new HashSet<TerenskeLokacije>();
        }

        [Key]
        public int IdSkole { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string NazivSkole { get; set; }
        public int MjestoPbr { get; set; }
        public int Organizator { get; set; }
        public int KontaktOsoba { get; set; }

        [ForeignKey("MjestoPbr")]
        [InverseProperty("Skole")]
        public virtual Mjesta MjestoPbrNavigation { get; set; }
        [InverseProperty("Skola")]
        public virtual ICollection<Edukacije> Edukacije { get; set; }
        [InverseProperty("Skola")]
        public virtual ICollection<PolazniciSkole> PolazniciSkole { get; set; }
        [InverseProperty("Skola")]
        public virtual ICollection<PrijavljeniPolazniciSkole> PrijavljeniPolazniciSkole { get; set; }

        [ForeignKey("SkoleId")]
        [InverseProperty("Skole")]
        public virtual ICollection<MaterijalnePotrebe> MaterijalnePotreb { get; set; }
        [ForeignKey("SkolaId")]
        [InverseProperty("Skola")]
        public virtual ICollection<TerenskeLokacije> TerenskaLokacija { get; set; }
    }
}