// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AkcijeSkole.DataAccess.SqlServer.Data.DbModels
{
    public partial class Aktivnosti
    {
        public Aktivnosti()
        {
            PolazniciAkcije = new HashSet<PolazniciAkcije>();
            PrijavljeniPolazniciAkcije = new HashSet<PrijavljeniPolazniciAkcije>();
        }

        public int IdAktivnost { get; set; }
        public int MjestoPbr { get; set; }
        public int KontaktOsoba { get; set; }
        public string Opis { get; set; }
        public int AkcijaId { get; set; }

        public virtual Akcije Akcija { get; set; }
        public virtual Mjesta MjestoPbrNavigation { get; set; }
        public virtual ICollection<PolazniciAkcije> PolazniciAkcije { get; set; }
        public virtual ICollection<PrijavljeniPolazniciAkcije> PrijavljeniPolazniciAkcije { get; set; }
    }
}