// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AkcijeSkole.DataAccess.SqlServer.Data.DbModels
{
    public partial class Edukacije
    {
        public Edukacije()
        {
            PolazniciSkole = new HashSet<PolazniciSkole>();
            Predavaci = new HashSet<Predavaci>();
            PrijavljeniPolazniciSkole = new HashSet<PrijavljeniPolazniciSkole>();
        }

        public int IdEdukacija { get; set; }
        public string NazivEdukacija { get; set; }
        public int MjestoPbr { get; set; }
        public string OpisEdukacije { get; set; }
        public int SkolaId { get; set; }

        public virtual Mjesta MjestoPbrNavigation { get; set; }
        public virtual Skole Skola { get; set; }
        public virtual ICollection<PolazniciSkole> PolazniciSkole { get; set; }
        public virtual ICollection<Predavaci> Predavaci { get; set; }
        public virtual ICollection<PrijavljeniPolazniciSkole> PrijavljeniPolazniciSkole { get; set; }
    }
}