// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AkcijeSkole.DataAccess.SqlServer.Data.DbModels
{
    public partial class MaterijalnePotrebe
    {
        public MaterijalnePotrebe()
        {
            Akcije = new HashSet<Akcije>();
            Skole = new HashSet<Skole>();
            TerenskeLokacije = new HashSet<TerenskeLokacije>();
        }

        [Key]
        public int IdMaterijalnePotrebe { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Naziv { get; set; }
        public int Organizator { get; set; }
        public int Davatelj { get; set; }
        public bool Zadovoljeno { get; set; }

        [ForeignKey("MaterijalnePotrebeId")]
        [InverseProperty("MaterijalnePotrebe")]
        public virtual ICollection<Akcije> Akcije { get; set; }
        [ForeignKey("MaterijalnePotrebId")]
        [InverseProperty("MaterijalnePotreb")]
        public virtual ICollection<Skole> Skole { get; set; }
        [ForeignKey("MaterijalnePotrebeId")]
        [InverseProperty("MaterijalnePotrebe")]
        public virtual ICollection<TerenskeLokacije> TerenskeLokacije { get; set; }
    }
}