// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AkcijeSkole.DataAccess.SqlServer.Data.DbModels
{
    public partial class Zahtjevi
    {
        public int IdZahtjev { get; set; }
        public int IdMatPotreba { get; set; }
        public string Status { get; set; }

        public virtual MaterijalnePotrebe IdMatPotrebaNavigation { get; set; }
    }
}